name: run unit test

on: [push]

jobs:
  run_phpunit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up PHP
      uses: php-actions/composer@v6
      with:
          php_version: '8.4'  # 指定 PHP 8.4
    - name: Run PHPunit
      uses: php-actions/phpunit@v3
      with:
        php_version: 8.4
        php_extensions: "xdebug sysvsem"
        configuration: "tests/phpunit.xml"
