name: run unit test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
      with:
          command: '-V'
    - name: composer install
      run: composer install
    - name: run phpunit
      run: chmod +x scripts/* -R && ./scripts/run_test.sh
